
####################################
######     Global start     ######
####################################
name                : 'Tralution'
title               : 'Tralution'
email               : demo@example.com
address             : ''
phone               : 
tagline             : 'description for your new site here' 
description: >- # this means to ignore newlines until "baseurl:"
  IT managed services and technology consulting.
baseurl             : "" # the subpath of your site, e.g. /blog
url                 : "https://tralution.com" #  7277783  the base hostname & protocol for your site, e.g. http://example.com
favicon: 'img/favicon.png'

paginate: 0
paginate_path: "/blog/page:num/"

sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown            : kramdown

# google_analytics
google_analytics: G-FZFME2XJ29

# disqus comment
disqus_shortname: softdash

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - gulpfile.js

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

####################################
######      Global end      ######
####################################


getform_id:  'e5e1f635-da5d-4fc9-9a47-2e10735146f5' # active contact https://getform.io/f/1234

mailchimp:
  user-id: 
  list-id: 

####################################
######        Copyright       ######
####################################
copyright_text: Copyright © 2021 All rights reserved to Tralution
company_url: 'https://tralution.com'


# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : G-FZFME2XJ29
    anonymize_ip         : # true, false (default)

#timezone: 'US' # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#google map api key

map: 
  key: 'AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA'
  let: 40.6700
  lng: -73.9400
  zoom: 11
  title: '121 King William Street, Snazzy'



# Collections
collections:
  posts:
    output: true
    permalink: /blog/:slug/
  pages:
    output: true
    permalink: /:path/index:output_ext

# Defaults
defaults:
  # _pages 
  - scope:
      path: "" # we can not defile path /blog/index.html for pagination
      type: pages
    values:
      layout: page
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      hero: blog_details
